from PySide6.QtWidgets import QWidget, QVBoxLayout, QLabel, QPushButton, QComboBox, QStackedWidget
from PySide6.QtCore import Signal
import numpy as np
import imageio # For general image loading

from modules.i_image_module import IImageModule


# --- Parameter Widgets for Different Operations ---
class BaseParamsWidget(QWidget):
    """Base class for parameter widgets to ensure a consistent interface."""
    def get_params(self) -> dict:
        raise NotImplementedError

class NoParamsWidget(BaseParamsWidget):
    """A placeholder widget for operations with no parameters."""
    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout(self)
        label = QLabel("This operation has no parameters.")
        label.setStyleSheet("font-style: italic; color: gray;")
        layout.addWidget(label)
        layout.addStretch()

    def get_params(self) -> dict:
        return {}


# Define a custom control widget
class ardyoControlsWidget(QWidget):
    # Signal to request processing from the module manager
    process_requested = Signal(dict)

    def __init__(self, module_manager, parent=None):
        super().__init__(parent)
        self.module_manager = module_manager
        self.param_widgets = {}
        self.setup_ui()

    def setup_ui(self):
        layout = QVBoxLayout(self)
        layout.addWidget(QLabel("<h3>Control Panel</h3>"))

        layout.addWidget(QLabel("Operation:"))
        self.operation_selector = QComboBox()
        layout.addWidget(self.operation_selector)

        # Stacked widget to hold the parameter UIs
        self.params_stack = QStackedWidget()
        layout.addWidget(self.params_stack)

        # Define operations and their corresponding parameter widgets
        operations = {
            "Vintage Film Look": NoParamsWidget,
        }

        for name, widget_class in operations.items():
            widget = widget_class()
            self.params_stack.addWidget(widget)
            self.param_widgets[name] = widget
            self.operation_selector.addItem(name)

        self.apply_button = QPushButton("Apply Processing")
        layout.addWidget(self.apply_button)

        self.apply_button.clicked.connect(self._on_apply_clicked)
        self.operation_selector.currentTextChanged.connect(self._on_operation_changed)

    def _on_apply_clicked(self):
        operation_name = self.operation_selector.currentText()
        active_widget = self.param_widgets[operation_name]
        params = active_widget.get_params()
        params['operation'] = operation_name # Add operation name to params
        self.process_requested.emit(params)

    def _on_operation_changed(self, operation_name: str):
        if operation_name in self.param_widgets:
            self.params_stack.setCurrentWidget(self.param_widgets[operation_name])


class ardyoImageModule(IImageModule):
    def __init__(self):
        super().__init__()
        self._controls_widget = None

    def get_name(self) -> str:
        return "ardyo Module"

    def get_supported_formats(self) -> list[str]:
        return ["png", "jpg", "jpeg", "bmp", "gif", "tiff"] # Common formats

    def create_control_widget(self, parent=None, module_manager=None) -> QWidget:
        if self._controls_widget is None:
            self._controls_widget = ardyoControlsWidget(module_manager, parent)
            # The widget's signal is connected to the module's handler
            self._controls_widget.process_requested.connect(self._handle_processing_request)
        return self._controls_widget

    def _handle_processing_request(self, params: dict):
        # Here, the module needs a way to trigger processing in the main app
        # The control widget now has a valid reference to the module manager
        if self._controls_widget and self._controls_widget.module_manager:
            self._controls_widget.module_manager.apply_processing_to_current_image(params)

    def load_image(self, file_path: str):
        try:
            image_data = imageio.imread(file_path)

            metadata = {'name': file_path.split('/')[-1]}
            return True, image_data, metadata, None # Session ID generated by store

        except Exception as e:
            print(f"Error loading 2D image {file_path}: {e}")
            return False, None, {}, None

    # ---------------------------------------------------------
    # Vintage Film Look helper functions
    # ---------------------------------------------------------

    def _apply_sepia(self, image_array):
        input_float = image_array.astype(np.float32)

        r = input_float[:, :, 0]
        g = input_float[:, :, 1]
        b = input_float[:, :, 2]

        sepia_r = 0.393 * r + 0.769 * g + 0.189 * b
        sepia_g = 0.349 * r + 0.686 * g + 0.168 * b
        sepia_b = 0.272 * r + 0.534 * g + 0.131 * b

        sepia_image = np.stack([sepia_r, sepia_g, sepia_b], axis=-1)

        return np.clip(sepia_image, 0, 255)

    def _add_warm_tint(self, image_array):
        input_float = image_array.astype(np.float32)

        output = input_float.copy()

        output[:, :, 0] = output[:, :, 0] * 1.08
        output[:, :, 1] = output[:, :, 1] * 1.02
        output[:, :, 2] = output[:, :, 2] * 0.88

        return np.clip(output, 0, 255)

    def _reduce_contrast(self, image_array, contrast=0.82):
        input_float = image_array.astype(np.float32)

        output = (input_float - 128) * contrast + 128

        return np.clip(output, 0, 255)

    def _fade_image(self, image_array, fade_amount=0.16):
        input_float = image_array.astype(np.float32)

        output = input_float * (1 - fade_amount) + 235 * fade_amount

        return np.clip(output, 0, 255)

    def _add_film_grain(self, image_array, strength=9):
        input_float = image_array.astype(np.float32)

        noise = np.random.normal(
            loc=0,
            scale=strength,
            size=input_float.shape
        )

        output = input_float + noise

        return np.clip(output, 0, 255)

    def _vintage_film_filter(self, image_data):
        input_float = image_data.astype(np.float32)

        original_was_grayscale = False

        if input_float.ndim == 2:
            original_was_grayscale = True
            rgb_image = np.stack([input_float, input_float, input_float], axis=-1)

        elif input_float.ndim == 3 and input_float.shape[2] in [3, 4]:
            rgb_image = input_float.copy()

        else:
            return image_data

        rgb_image = rgb_image[:, :, :3]

        # Apply vintage color and aging effects
        vintage_image = self._apply_sepia(rgb_image)
        vintage_image = self._add_warm_tint(vintage_image)
        vintage_image = self._reduce_contrast(vintage_image, contrast=0.82)
        vintage_image = self._fade_image(vintage_image, fade_amount=0.16)
        vintage_image = self._add_film_grain(vintage_image, strength=9)

        vintage_image = np.clip(vintage_image, 0, 255)

        # Preserve alpha channel if original image has transparency
        if image_data.ndim == 3 and image_data.shape[2] == 4:
            result_rgba = np.zeros_like(input_float, dtype=np.float32)
            result_rgba[:, :, :3] = vintage_image[:, :, :3]
            result_rgba[:, :, 3] = input_float[:, :, 3]
            return np.clip(result_rgba, 0, 255)

        # Return grayscale if original image was grayscale
        if original_was_grayscale:
            return np.mean(vintage_image, axis=2)

        return vintage_image

    def process_image(self, image_data: np.ndarray, metadata: dict, params: dict) -> np.ndarray:
        processed_data = image_data.copy()

        operation = params.get('operation')

        if operation == "Vintage Film Look":
            processed_data = self._vintage_film_filter(processed_data)

        # Ensure output data type is consistent
        processed_data = np.clip(processed_data, 0, 255)
        processed_data = processed_data.astype(image_data.dtype)

        return processed_data